import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Cursor.HAND_CURSOR;
import java.awt.Graphics;

import javax.swing.JLabel;


/**
 *
 * @author ferna
 */
public class U2P1_tap2_minipaint extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public U2P1_tap2_minipaint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jLabel1.setText("Etiqueta de info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // <evento cuando haces click
        
        JLabel lbl_info;
        lbl_info.setText(String.format("Realizaste click en: [%d, %d]", evt.getX(), evt.getY());
        //getX()Obtiene la coordenada de X relativa al JPanel
        //getY()Obtiene la coordenada de Y relativa al JPanel
    }                                    

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {                                     
        JLabel lbl_info;
        // Se ejecuta cuando el cursor entra al area del JPanel1
        lbl_info.setText(String.format("El mouse entro al JPanel1");
        //Cambia el color de fondo del JPanel1 a rojo
        jPanel1.setBackground(Color.red);        
    }                                    

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {                                    
        JLabel lbl_info;
        // Se ejecuta cuando el cursor sale del area del JPanel1
        lbl_info.setText(String.format("El mouse a salido del JPanel1"));
        //Cambia el color del fondo de JPanel a Azul
        jPanel1.setBackground(Color.blue);
    }                                   

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {                                     
        // Se ejecuta cuando presionas el boton del mouse en el area del JPanel
        Graphics grafico = getGraphics();
        //Cambia el color del dibujo (JPanel) a rojo
        grafico.setColor(Color.red);
        //Se dibuja EXACTAMENTE EN LA POSICIÓN REAL DEL MOUSE
        grafico.fillRect(evt.getX(), evt.getY(), 5, 5);
        //Libera recursos de los graficos 
        grafico.dispose();
    }                                    

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {                                      
        // Se ejecuta cuando sueltas el boton del mouse 
        Graphics grafico = jPanel1.getGraphics();
        grafico.setColor(Color.green);
        
        //Vamos a dibujar un rectangulo verde en la posición real del mouse
        grafico.fillRect(evt.getX(), evt.getY(), 5, 5);
        grafico.dispose();
    }                                     

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {                                     
        // Evento por descubrir
        Graphics grafico = jPanel1.getGraphics();
        grafico.setColor(Color.white);
        //Dibiuja un ovalo blanco...
        //El fillOval dibuja un ovalo
        grafico.fillOval(evt.getX(), evt.getY(), 10, 10);
        grafico.dispose();
    }                                    

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {                                   
        // Evento por descubrir
        this.jPanel1.setCursor(new Cursor(HAND_CURSOR));
    }                                  


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
